@echo off
setlocal enabledelayedexpansion
echo === BT Override Card Generator Build ===
echo.

REM -- Parse version from src/version.py -------------------------------
for /f "usebackq tokens=2 delims= " %%a in (`python -c "import re; print(re.search(r'__version__\s*=\s*\"([^\"]+)\"', open('src/version.py').read()).group(1))"`) do set VERSION=%%a
if "%VERSION%"=="" set VERSION=0.1.0
echo Building version: %VERSION%

REM -- Generate version_metadata.txt -----------------------------------
echo Generating version_metadata.txt...
python -c "import re; v=re.search(r'__version__\s*=\s*\"([^\"]+)\"', open('src/version.py').read()).group(1); parts=v.split('.'); parts+=(['0']*(4-len(parts))); iv=[str(int(x)) for x in parts]; print(f'''# UTF-8
#
# Windows version resource for PyInstaller.
# Auto-generated by build.bat — do not edit by hand.
#
vsVersionInfo = (
    FixedFileInfo(
        filevers=({', '.join(iv)}),
        prodvers=({', '.join(iv)}),
        mask=0x3f,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0)
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    '040904B0',
                    [
                        StringStruct('CompanyName', 'BT Override'),
                        StringStruct('FileVersion', '{v}.0'),
                        StringStruct('InternalName', 'BTOverrideCardGenerator'),
                        StringStruct('LegalCopyright', ''),
                        StringStruct('OriginalFilename', 'BTOverrideCardGenerator.exe'),
                        StringStruct('ProductName', 'BT Override Card Generator'),
                        StringStruct('ProductVersion', '{v}.0'),
                    ]
                )
            ]
        ),
        VarFileInfo([VarStruct('Translation', [1033, 1200])])
    ]
)''')" > version_metadata.txt

REM -- Clean build venv ------------------------------------------------
if not exist .venv_build (
    echo Creating clean build venv...
    python -m venv .venv_build
)

echo Installing dependencies...
.venv_build\Scripts\pip install --quiet PyQt6>=6.6.0 PyYAML>=6.0.1 reportlab>=4.1.0 Pillow>=10.0.0 pyinstaller>=6.0 certifi

echo.
echo Building BT Override Card Generator...
.venv_build\Scripts\pyinstaller bt_override.spec --clean

REM -- Create release zip ----------------------------------------------
echo.
echo Creating release zip...
if not exist dist\Release mkdir dist\Release

REM Remove user data from dist so it does not end up in the zip
if exist "dist\BT_Override_Card_Generator\data\profiles" rmdir /S /Q "dist\BT_Override_Card_Generator\data\profiles"

powershell -Command "Compress-Archive -Path 'dist\BT_Override_Card_Generator\*' -DestinationPath 'dist\Release\BT_Override_Card_Generator_v%VERSION%.zip' -Force"

echo.
echo Build complete.
echo Distribution:  dist\BT_Override_Card_Generator\
echo Release zip:   dist\Release\BT_Override_Card_Generator_v%VERSION%.zip
pause
