"""Generate version_metadata.txt for PyInstaller Windows version resource.

Called by build.bat — not intended to be run directly.
Reads __version__ from src/version.py, writes version_metadata.txt.
Prints version string to stdout for build.bat capture.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# -- Read version from src/version.py ----------------------------------------
version_py = ROOT / "src" / "version.py"
content = version_py.read_text(encoding="utf-8")
version = re.search(r'__version__\s*=\s*"([^"]+)"', content).group(1)

# -- Split into integer parts, pad to 4 -------------------------------------
parts = version.split(".")
parts += ["0"] * (4 - len(parts))
iv = [str(int(x)) for x in parts]

# -- Write PyInstaller version resource --------------------------------------
metadata = f"""# UTF-8
#
# Windows version resource for PyInstaller.
# Auto-generated by build.bat — do not edit by hand.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({', '.join(iv)}),
    prodvers=({', '.join(iv)}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'BT Override'),
            StringStruct('FileVersion', '{version}.0'),
            StringStruct('InternalName', 'BTOverrideCardGenerator'),
            StringStruct('LegalCopyright', ''),
            StringStruct('OriginalFilename', 'BTOverrideCardGenerator.exe'),
            StringStruct('ProductName', 'BT Override Card Generator'),
            StringStruct('ProductVersion', '{version}.0'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

output_txt = ROOT / "version_metadata.txt"
output_txt.write_text(metadata, encoding="utf-8")

# First stdout line MUST be the version string — build.bat captures it with for /f.
print(version)
