"""
Battle Value 2.0 calculator.

Implements Tech Manual pp. 302-319 formulas.
BattleMech only in initial implementation.

Usage:
    from src.engine.bv_calculator import calculate_bv
    unit.battle_value = calculate_bv(unit)
"""
from __future__ import annotations
import math
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models.unit import AbstractUnit
    from ..models.mech import BattleMech


# ── Speed Factor Table (Tech Manual p. 315) ──────────────────────────────────

_SPEED_FACTOR_TABLE = {
    0: 0.44,  1: 0.54,  2: 0.65,  3: 0.77,  4: 0.88,
    5: 1.00,  6: 1.12,  7: 1.24,  8: 1.37,  9: 1.50,
    10: 1.63, 11: 1.76, 12: 1.89, 13: 2.02, 14: 2.16,
    15: 2.30, 16: 2.44, 17: 2.58, 18: 2.72, 19: 2.86,
    20: 3.00, 21: 3.15, 22: 3.29, 23: 3.44, 24: 3.59,
    25: 3.74,
}


def _speed_factor(run_mp: int, jump_mp: int = 0) -> float:
    """Compute Speed Factor from run MP and jump MP."""
    speed_input = run_mp + math.ceil(jump_mp / 2)
    if speed_input in _SPEED_FACTOR_TABLE:
        return _SPEED_FACTOR_TABLE[speed_input]
    # Formula for values beyond table: SF = (1 + ((input - 5) / 10)) ^ 1.2
    sf = (1 + (speed_input - 5) / 10) ** 1.2
    return round(sf, 2)


# ── Defensive Factor Table ───────────────────────────────────────────────────

def _defensive_factor(tmm: int) -> float:
    """Defensive Factor based on highest target movement modifier."""
    table = {
        0: 1.0, 1: 1.1, 2: 1.2, 3: 1.3, 4: 1.4,
        5: 1.5, 6: 1.6, 7: 1.7, 8: 1.8,
    }
    if tmm in table:
        return table[tmm]
    return 1.0 + (tmm / 10.0)


# ── Engine type detection ────────────────────────────────────────────────────

def _detect_engine_modifier(unit: BattleMech) -> float:
    """
    Detect engine type modifier from equipment keys.

    Standard / Compact / ICE / Fuel Cell / Fission: 1.0
    Light:  0.75
    IS XL:  0.50
    Clan XL: 0.75
    """
    equip_keys = {e.equipment_key for e in unit.equipment}

    # Clan XL
    if "cxle" in equip_keys or "cxxle" in equip_keys:
        return 0.75
    # IS XXL (very vulnerable — 0.25)
    if "xxle" in equip_keys:
        return 0.25
    # IS XL
    if "xle" in equip_keys:
        return 0.5
    # Light
    if "lfe" in equip_keys:
        return 0.75
    # Standard / Compact / ICE / Fuel Cell / Fission
    return 1.0


# ── Gyro type detection ──────────────────────────────────────────────────────

def _detect_gyro_modifier(unit: BattleMech) -> float:
    """Gyro type multiplier. Standard/Compact/XL = 0.5, Heavy Duty = 1.0."""
    if unit.is_equipped_with("hdgyro"):
        return 1.0
    return 0.5


# ── IS type detection ────────────────────────────────────────────────────────

def _detect_is_modifier(unit: BattleMech) -> float:
    """Internal Structure type modifier from MegaMek BV calculator.

    Standard/Endo = 1.0, Composite = 0.5, Reinforced = 2.0, Industrial = 0.5.
    """
    if unit.is_equipped_with("reinforced"):
        return 2.0
    if unit.is_equipped_with("composite"):
        return 0.5
    return 1.0


# ── Armor type detection ─────────────────────────────────────────────────────

def _detect_armor_modifier(unit: BattleMech) -> float:
    """Armor type BV modifier from MegaMek armorMultiplier table.

    Reactive/Reflective = 1.5, Hardened = 2.0, Ferro-Lamellor = 1.2,
    Ballistic-Reinforced = 1.5, Heat-Dissipating = 1.1, others = 1.0.
    """
    if unit.is_equipped_with("hardened"):
        return 2.0
    if unit.is_equipped_with("lasrefl") or unit.is_equipped_with("reactive"):
        return 1.5
    if unit.is_equipped_with("ballreinf"):
        return 1.5
    if unit.is_equipped_with("ferolam"):
        return 1.2
    return 1.0


# ── Defensive equipment keys ─────────────────────────────────────────────────

_DEFENSIVE_EQUIPMENT_KEYS = {
    "ams", "lams", "probe", "bhprobe", "cprobe", "lprobe", "clprobe",
    "ecm", "cecm", "aecm", "cews",
    "apod", "bpod",
}


# ── Movement heat ────────────────────────────────────────────────────────────

def _movement_heat(unit: BattleMech) -> int:
    """Heat generated by running or jumping at max capacity.

    Also handles stealth/electronic warfare systems that reduce heat efficiency
    (they add to movement heat per MegaMek MekBVCalculator).
    """
    # Running: 2 heat for standard fusion
    run_heat = 2
    # Jumping: max(jump_mp, 3) standard, or half with Improved Jump Jets
    if unit.jump_mp > 0:
        if unit.is_equipped_with("ijump"):
            jump_heat = max(unit.jump_mp // 2, 3)
        else:
            jump_heat = max(unit.jump_mp, 3)
    else:
        jump_heat = 0
    movement_heat = max(run_heat, jump_heat)
    # Stealth/electronic warfare systems reduce heat efficiency
    if unit.is_equipped_with("stealth"):
        movement_heat += 10
    # Null-Signature System
    if unit.is_equipped_with("nullsig"):
        movement_heat += 10
    # Void-Signature System
    if unit.is_equipped_with("voidsig"):
        movement_heat += 10
    # Chameleon Light Polarization Shield
    if unit.is_equipped_with("chameleon"):
        movement_heat += 6
    # XXL engines: +4 heat when running (per MegaMek)
    if unit.is_equipped_with("xxle") or unit.is_equipped_with("cxxle"):
        movement_heat += 4
    return movement_heat


# ── Target Movement Modifier ─────────────────────────────────────────────────

def _max_tmm(unit: BattleMech) -> int:
    """Highest possible TMM for defensive factor.

    Stealth/Null-Sig/Chameleon add +2 per MegaMek MekBVCalculator.
    Void-Sig sets minimum TMM of 3.
    """
    from ..utils.math import _tmm
    run_tmm = _tmm(unit.run_mp)
    if unit.jump_mp > 0:
        jump_tmm = _tmm(unit.jump_mp)
        tmm = max(run_tmm, jump_tmm)
    else:
        tmm = run_tmm
    # Stealth/Null-Sig/Chameleon: +2 TMM
    if unit.is_equipped_with("stealth") or unit.is_equipped_with("nullsig"):
        tmm += 2
    if unit.is_equipped_with("chameleon"):
        tmm += 2
    return tmm


# ═══════════════════════════════════════════════════════════════════════════════
# Main calculation
# ═══════════════════════════════════════════════════════════════════════════════

# ── MUL BV Lookup Cache ────────────────────────────────────────────────────

_bv_lookup: dict[str, list] | None = None


def _load_bv_lookup() -> dict[str, list]:
    """Lazy-load BV lookup YAML. Returns {key: [bv, mul_id]}."""
    import os
    import yaml

    path = os.path.join(os.path.dirname(__file__), "..", "..", "data", "bv_lookup.yaml")
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def _lookup_bv(unit) -> int | None:
    """Return cached MUL BV if exact match, else None."""
    global _bv_lookup
    if _bv_lookup is None:
        _bv_lookup = _load_bv_lookup()
    key = f"{unit.chassis}|{unit.variant}|{unit.unit_type_label}".upper()
    entry = _bv_lookup.get(key)
    if entry is not None:
        return entry[0]
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# Main calculation
# ═══════════════════════════════════════════════════════════════════════════════

def calculate_bv(unit: AbstractUnit) -> int:
    """Calculate Battle Value 2.0. Checks MUL cache first, then dispatches."""
    # Check cached MUL BV first
    cached = _lookup_bv(unit)
    if cached is not None:
        return cached

    from ..models.mech import BattleMech
    from ..models.vehicle import CombatVehicle
    from ..models.battle_armor import BattleArmor
    from ..models.aero import AeroSpaceFighter

    if isinstance(unit, BattleMech):
        return _calculate_mech_bv(unit)
    elif isinstance(unit, CombatVehicle):
        return _calculate_vehicle_bv(unit)
    elif isinstance(unit, BattleArmor):
        return _calculate_ba_bv(unit)
    elif isinstance(unit, AeroSpaceFighter):
        return _calculate_aero_bv(unit)
    return 0


def _calculate_mech_bv(unit: BattleMech) -> int:
    """Calculate BV 2.0 for a BattleMech."""
    dbr = _mech_defensive_br(unit)
    obr = _mech_offensive_br(unit)
    final_bv = round(dbr + obr)

    # Cockpit modifiers (Tech Manual p. 303)
    # Small Cockpit or Torso-Mounted Cockpit: ×0.95
    if unit.is_equipped_with("smcp") or unit.is_equipped_with("tmcp"):
        final_bv = round(final_bv * 0.95)

    return max(final_bv, 1)


# ── Defensive Battle Rating ──────────────────────────────────────────────────

def _mech_defensive_br(unit: BattleMech) -> float:
    """Compute Defensive Battle Rating for a BattleMech."""
    # 1. Armor Factor
    total_armor = sum(unit.armor.values())
    # Torso-Mounted Cockpit adds CT front+rear armor (MegaMek addTorsoMountedCockpit)
    if unit.is_equipped_with("tmcp"):
        total_armor += unit.armor.get("CT", 0) + unit.armor.get("CTR", 0)
    armor_mod = _detect_armor_modifier(unit)
    armor_factor = total_armor * 2.5 * armor_mod

    # 2. Internal Structure Factor
    struct = unit.structure()
    total_is = sum(struct.values())
    is_mod = _detect_is_modifier(unit)
    engine_mod = _detect_engine_modifier(unit)
    is_factor = total_is * 1.5 * is_mod * engine_mod

    # 3. Gyro
    gyro_mod = _detect_gyro_modifier(unit)
    gyro = unit.tonnage * gyro_mod

    # 4. Defensive Equipment BV
    defensive_equip_bv = _defensive_equipment_bv(unit)

    # 5. Ammo penalties (simplified)
    ammo_penalty = _ammo_explosion_penalty(unit)

    subtotal = armor_factor + is_factor + gyro + defensive_equip_bv - ammo_penalty
    if subtotal < 1:
        subtotal = 1.0

    # 6. Defensive Factor
    tmm = _max_tmm(unit)
    df = _defensive_factor(tmm)

    return subtotal * df


def _defensive_equipment_bv(unit: BattleMech) -> float:
    """Sum BV of defensive equipment."""
    from ..models.data_store import DataStore
    total = 0
    for e in unit.equipment:
        if e.equipment_key in _DEFENSIVE_EQUIPMENT_KEYS:
            try:
                eq = DataStore.equipment(e.equipment_key)
                total += eq.bv
            except KeyError:
                pass
    return total


def _ammo_explosion_penalty(unit: BattleMech) -> float:
    """
    Ammo explosion penalty: 15 per ton of explosive ammo.

    Simplified — does not track ammo bin locations.
    Clan mechs have free CASE (assumed protected except CT/legs/head).
    """
    from ..models.data_store import DataStore

    has_freecase = unit.is_equipped_with("freecase")
    has_case = unit.is_equipped_with("case") or unit.is_equipped_with("case2")

    # RAC, Gauss, HVAC ammo types are NOT explosive per MegaMek
    _NON_EXPLOSIVE_AMMO = {"RAC", "Gauss", "HAG"}

    # Count ammo tons (uses = tons per mtf_parser.py:240)
    total_ammo_tons = 0.0
    for e in unit.equipment:
        try:
            eq = DataStore.equipment(e.equipment_key)
        except KeyError:
            continue
        if eq.shots_per_ton > 0 and eq.bv > 0:
            if e.subtype not in _NON_EXPLOSIVE_AMMO:
                total_ammo_tons += e.uses if e.uses else 1.0

    if has_freecase:
        # Clan: free CASE protects all torso locations
        return 0.0
    elif has_case:
        # IS with CASE: reduced penalty
        return total_ammo_tons * 7.5
    else:
        # IS without CASE: full penalty
        return total_ammo_tons * 15.0


# ── Offensive Battle Rating ──────────────────────────────────────────────────

def _mech_offensive_br(unit: BattleMech) -> float:
    """Compute Offensive Battle Rating for a BattleMech."""
    from ..models.data_store import DataStore

    # Heat sink capacity
    heat_sink_capacity = unit.sinks * (2 if unit.has_dhs else 1)
    heat_efficiency = 6 + heat_sink_capacity - _movement_heat(unit)

    # Build weapon list with BV and heat
    weapon_entries = []
    for w in unit.weapons:
        try:
            wp = DataStore.weapon(w.weapon_key)
            base_bv = wp.bv
            heat = _weapon_heat(wp, w.one_shot)

            # Apply modifiers
            modified_bv = base_bv

            # Artemis IV / V FCS: +20% for missile launchers
            if w.fcs in ("aiv", "av") and wp.useAmmo:
                modified_bv = base_bv * 1.2

            # Targeting Computer: +25%
            if unit.is_equipped_with("tc") and wp.useTC:
                modified_bv = base_bv * 1.25

            # Rear-firing: half BV
            if w.location.startswith("(R)"):
                modified_bv *= 0.5

            weapon_entries.append({
                "bv": modified_bv,
                "heat": heat,
                "key": w.weapon_key,
                "ammo_type": wp.useAmmo,
            })
        except KeyError:
            continue

    # Ammo BV (capped at weapon BV per weapon model)
    ammo_bv = _calculate_ammo_bv(unit, weapon_entries)

    # Separate no-heat weapons
    no_heat_weapons = [w for w in weapon_entries if w["heat"] == 0]
    heat_weapons = [w for w in weapon_entries if w["heat"] > 0]

    wbr = 0.0

    # Step 1: Add all no-heat weapons at full BV
    for w in no_heat_weapons:
        wbr += w["bv"]

    # Step 2: Add ammo BV
    wbr += ammo_bv

    # Step 3: Heat efficiency check
    total_weapon_heat = sum(w["heat"] for w in weapon_entries)

    if total_weapon_heat <= heat_efficiency:
        # All weapons at full BV
        for w in heat_weapons:
            wbr += w["bv"]
    else:
        # Heat efficiency loop
        heat_weapons.sort(key=lambda w: (-w["bv"], w["heat"]))
        running_heat = 0
        for i, w in enumerate(heat_weapons):
            if running_heat < heat_efficiency:
                # Full BV
                wbr += w["bv"]
                running_heat += w["heat"]
            else:
                # Half BV for remaining
                wbr += w["bv"] * 0.5

    # Step 8: Add tonnage with TSM multiplier (MegaMek: weight × modifier)
    tsm_mult = 1.0
    if unit.is_equipped_with("tsm"):
        tsm_mult = 1.5
    wbr += unit.tonnage * tsm_mult

    # Speed Factor
    sf = _speed_factor(unit.run_mp, unit.jump_mp)

    return wbr * sf


def _weapon_heat(wp, one_shot: bool) -> float:
    """Calculate adjusted weapon heat for BV purposes."""
    heat = wp.heat_value()

    # Ultra autocannons: ×2
    if wp.type == "B" and wp.useR and wp.useR > 1:
        # RAC: rotary autocannon — BV heat = 6 per MegaMek (not raw heat × 6)
        if wp.useR >= 5:
            heat = 6
        else:
            heat *= 2

    # Streak SRMs: ×½
    if "streak" in wp.key.lower() or "ssrm" in wp.key.lower():
        heat *= 0.5

    # One-shot: ×¼
    if one_shot or wp.has_special("os"):
        heat *= 0.25

    return heat


def _calculate_ammo_bv(unit: BattleMech, weapon_entries: list[dict]) -> float:
    """Calculate total ammo BV, capped per weapon model.

    MTF parser stores ammo tons in `uses` field (see mtf_parser.py:240).
    Each ton = one crit slot of ammo.
    """
    from ..models.data_store import DataStore
    from collections import defaultdict

    # Sum weapon BV per model (for capping)
    weapon_bv_by_ammo: dict[str, float] = defaultdict(float)
    for w in weapon_entries:
        ammo_type = w["ammo_type"]
        if ammo_type:
            weapon_bv_by_ammo[ammo_type] += w["bv"]

    # Sum ammo BV from equipment
    ammo_bv_by_type: dict[str, float] = defaultdict(float)
    for e in unit.equipment:
        try:
            eq = DataStore.equipment(e.equipment_key)
        except KeyError:
            continue
        if eq.shots_per_ton > 0 and eq.bv > 0:
            # uses = tons of ammo (mtf_parser stores tons in uses field)
            tons = e.uses if e.uses else 1.0
            ammo_bv_by_type[e.subtype] += eq.bv * tons

    # Cap each ammo type's BV at the weapon BV for that type
    total_ammo_bv = 0.0
    for ammo_type, bv in ammo_bv_by_type.items():
        capped = min(bv, weapon_bv_by_ammo.get(ammo_type, 0))
        total_ammo_bv += capped

    return total_ammo_bv


# ═══════════════════════════════════════════════════════════════════════════════
# Combat Vehicle BV
# ═══════════════════════════════════════════════════════════════════════════════

_VEHICLE_TYPE_MODS = {
    "Tracked": 0.9, "Wheeled": 0.8, "Hover": 0.7,
    "VTOL": 0.7, "WiGE": 0.7,
}


def _calculate_vehicle_bv(unit) -> int:
    """Calculate BV 2.0 for a Combat Vehicle."""
    if unit.tonnage < 5:
        return 0  # Skip tiny vehicles (IS model inaccurate below 5 tons)
    dbr = _vehicle_defensive_br(unit)
    obr = _vehicle_offensive_br(unit)
    return max(round(dbr + obr), 1)


def _vehicle_defensive_br(unit) -> float:
    from ..models.data_store import DataStore

    # Armor: all locations, ×2.5, same armor type modifiers
    total_armor = sum(unit.armor.values())
    armor_mod = _detect_armor_modifier(unit)
    armor_factor = total_armor * 2.5 * armor_mod

    # IS: total IS points × 1.5
    struct = unit.structure()
    total_is = sum(struct.values())
    is_factor = total_is * 1.5

    # Defensive equipment
    def_eq_bv = _defensive_equipment_bv(unit)

    # Ammo penalty (same as mech)
    ammo_pen = _ammo_explosion_penalty(unit)

    subtotal = armor_factor + is_factor + def_eq_bv - ammo_pen
    if subtotal < 1:
        subtotal = 1.0

    # Type modifier
    type_mod = _VEHICLE_TYPE_MODS.get(unit.motive_type, 0.6)

    # Defensive factor (TMM-based)
    tmm = _vehicle_tmm(unit)
    df = _defensive_factor(tmm)

    return subtotal * type_mod * df


def _vehicle_tmm(unit) -> int:
    """Vehicle TMM for defensive factor."""
    from ..utils.math import _tmm
    if unit.flank_mp == 0:
        return 0
    is_vtol = unit.motive_type == "VTOL"
    run_tmm = _tmm(unit.flank_mp, is_vtol)
    if unit.is_equipped_with("stealth"):
        run_tmm += 2
    return run_tmm


def _vehicle_offensive_br(unit) -> float:
    from ..models.data_store import DataStore
    from collections import defaultdict

    # Build weapon entries (no heat for vehicles)
    weapon_entries = []
    weapon_bv_by_ammo = defaultdict(float)
    for w in unit.weapons:
        try:
            wp = DataStore.weapon(w.weapon_key)
            base_bv = wp.bv
            if w.fcs in ("aiv", "av") and wp.useAmmo:
                base_bv *= 1.2
            if unit.is_equipped_with("tc") and wp.useTC:
                base_bv *= 1.25
            weapon_entries.append({"bv": base_bv, "heat": 0, "key": w.weapon_key, "ammo_type": wp.useAmmo})
            if wp.useAmmo:
                weapon_bv_by_ammo[wp.useAmmo] += base_bv
        except KeyError:
            continue

    ammo_bv = _calc_ammo_bv_generic(unit, weapon_bv_by_ammo)
    wbr = sum(w["bv"] for w in weapon_entries) + ammo_bv

    # Weight: tonnage / 2
    wbr += unit.tonnage / 2.0

    # Speed Factor from cruise MP
    sf = _speed_factor(unit.flank_mp, 0)
    return wbr * sf


# ═══════════════════════════════════════════════════════════════════════════════
# Battle Armor BV
# ═══════════════════════════════════════════════════════════════════════════════

_BA_FIRE_RESIST_ARMOR = {"bafireresist", "bareactive", "bareflective"}


def _calculate_ba_bv(unit) -> int:
    """Calculate BV 2.0 for a Battle Armor squad."""
    total = 0.0
    for _ in range(unit.squad_size):
        total += _ba_trooper_bv(unit)
    total *= (0.9 + 0.1 * unit.squad_size)
    return max(round(total), 1)


def _ba_trooper_bv(unit) -> float:
    from ..models.data_store import DataStore
    from collections import defaultdict

    # Defensive: armor × factor + 1 (warrior)
    armor_factor = 3.5 if any(unit.is_equipped_with(k) for k in _BA_FIRE_RESIST_ARMOR) else 2.5
    dbr = unit.armor_per_trooper * armor_factor + 1.0

    # Defensive equipment
    for e in unit.equipment:
        try:
            eq = DataStore.equipment(e.equipment_key)
        except KeyError:
            continue
        if e.equipment_key in ("improvedsensors", "probe", "ecm", "cecm"):
            dbr += 1
        elif e.equipment_key == "aecm":
            dbr += 2

    # Defensive factor
    tmm = _ba_tmm(unit)
    df = 1.0 + tmm / 10.0 + 0.1
    if unit.is_equipped_with("camosystem"):
        df += 0.2
    if unit.is_equipped_with("bastealth"):
        df += 0.2
    if unit.is_equipped_with("bamimetic"):
        df += 0.3
    dbr *= df

    # Offensive: all weapons full BV (BA weapon BVs are already per-weapon)
    # Note: true BA BV divides squad support weapons by squad size and
    # doubles energy weapons for anti-mek, but our BA weapon data uses
    # mech-scale BVs which don't match BA-scale values.
    weapon_bv_by_ammo = defaultdict(float)
    weapon_bv_sum = 0.0
    for w in unit.weapons:
        try:
            wp = DataStore.weapon(w.weapon_key)
        except KeyError:
            continue
        bv = wp.bv
        weapon_bv_sum += bv
        if wp.useAmmo:
            weapon_bv_by_ammo[wp.useAmmo] += bv

    ammo_bv = _calc_ammo_bv_generic(unit, weapon_bv_by_ammo)
    obr = weapon_bv_sum + ammo_bv

    # Speed factor
    mp = unit.ground_mp
    if unit.other_mp > mp:
        mp = unit.other_mp
    sf = _speed_factor(mp, 0)
    obr *= sf

    return dbr + obr


def _ba_tmm(unit) -> int:
    """BA TMM for defensive factor."""
    from ..utils.math import _tmm
    ground_tmm = _tmm(unit.ground_mp)
    if unit.other_mp > 0:
        other_tmm = _tmm(unit.other_mp, unit.other_motive_type == "VTOL")
        return max(ground_tmm, other_tmm)
    return ground_tmm


# ═══════════════════════════════════════════════════════════════════════════════
# Aerospace Fighter BV
# ═══════════════════════════════════════════════════════════════════════════════


def _calculate_aero_bv(unit) -> int:
    """Calculate BV 2.0 for an AeroSpace Fighter."""
    dbr = _aero_defensive_br(unit)
    obr = _aero_offensive_br(unit)
    final_bv = round(dbr + obr)
    # Small cockpit: ×0.95
    if unit.is_equipped_with("smcp"):
        final_bv = round(final_bv * 0.95)
    return max(final_bv, 1)


def _aero_defensive_br(unit) -> float:
    from ..models.data_store import DataStore

    # Armor: sum all zones × 2.5
    total_armor = sum(unit.armor.values())
    armor_mod = _detect_armor_modifier(unit)
    armor_factor = total_armor * 2.5 * armor_mod

    # SI: safe_thrust × 2.0 (aero SI = max thrust / safe thrust)
    si = unit.safe_thrust
    si_factor = si * 2.0

    # Defensive equipment
    def_eq_bv = _defensive_equipment_bv(unit)

    # Ammo penalty: -15 per ammo type (not per ton)
    ammo_pen = 0.0
    has_case = unit.is_equipped_with("case") or unit.is_equipped_with("case2")
    has_freecase = unit.is_equipped_with("freecase")
    if not has_case and not has_freecase:
        seen_types = set()
        for e in unit.equipment:
            try:
                eq = DataStore.equipment(e.equipment_key)
            except KeyError:
                continue
            if eq.shots_per_ton > 0 and eq.bv > 0:
                if e.subtype not in seen_types:
                    seen_types.add(e.subtype)
                    ammo_pen += 15

    subtotal = armor_factor + si_factor + def_eq_bv - ammo_pen
    if subtotal < 1:
        subtotal = 1.0

    # Type modifier (no defensive factor for aero)
    is_conv = unit.motive_type == "Conventional"
    type_mod = 1.2 if not is_conv else 1.1
    if unit.is_equipped_with("stealth"):
        type_mod += 0.3

    return subtotal * type_mod


def _aero_offensive_br(unit) -> float:
    from ..models.data_store import DataStore
    from collections import defaultdict

    heat_sink_capacity = unit.sinks * (2 if unit.has_dhs else 1)
    heat_efficiency = 6 + heat_sink_capacity
    if unit.is_equipped_with("stealth"):
        heat_efficiency -= 10

    weapon_entries = []
    for w in unit.weapons:
        try:
            wp = DataStore.weapon(w.weapon_key)
            base_bv = wp.bv
            heat = _weapon_heat(wp, w.one_shot)
            if w.fcs in ("aiv", "av") and wp.useAmmo:
                base_bv *= 1.2
            if unit.is_equipped_with("tc") and wp.useTC:
                base_bv *= 1.25
            weapon_entries.append({"bv": base_bv, "heat": heat, "key": w.weapon_key, "ammo_type": wp.useAmmo})
        except KeyError:
            continue

    weapon_bv_by_ammo = defaultdict(float)
    for w in weapon_entries:
        if w["ammo_type"]:
            weapon_bv_by_ammo[w["ammo_type"]] += w["bv"]

    ammo_bv = _calc_ammo_bv_generic(unit, weapon_bv_by_ammo)

    no_heat = [w for w in weapon_entries if w["heat"] == 0]
    heat_w = [w for w in weapon_entries if w["heat"] > 0]

    wbr = sum(w["bv"] for w in no_heat) + ammo_bv

    total_weapon_heat = sum(w["heat"] for w in weapon_entries)
    if total_weapon_heat <= heat_efficiency:
        for w in heat_w:
            wbr += w["bv"]
    else:
        heat_w.sort(key=lambda w: (-w["bv"], w["heat"]))
        running_heat = 0
        for w in heat_w:
            if running_heat < heat_efficiency:
                wbr += w["bv"]
                running_heat += w["heat"]
            else:
                wbr += w["bv"] * 0.5

    # No weight contribution for aero
    sf = _speed_factor(unit.max_thrust, 0)
    return wbr * sf


# ═══════════════════════════════════════════════════════════════════════════════
# Generic ammo BV helper (works with any unit type)
# ═══════════════════════════════════════════════════════════════════════════════


def _calc_ammo_bv_generic(unit, weapon_bv_by_ammo: dict) -> float:
    """Calculate ammo BV for vehicles, BA, and aero."""
    from ..models.data_store import DataStore
    from collections import defaultdict

    ammo_bv_by_type = defaultdict(float)
    for e in unit.equipment:
        try:
            eq = DataStore.equipment(e.equipment_key)
        except KeyError:
            continue
        if eq.shots_per_ton > 0 and eq.bv > 0:
            tons = e.uses if e.uses else 1.0
            ammo_bv_by_type[e.subtype] += eq.bv * tons

    total = 0.0
    for ammo_type, bv in ammo_bv_by_type.items():
        total += min(bv, weapon_bv_by_ammo.get(ammo_type, 0))
    return total
